Fix #838 : Kafka in TLS (not only mutual TLS)
buger/goreplay pull request #839
Opened 2020-10-19 11:52 UTC by davidFR

Allowing to connect to a TLS Kafka (only server certificate, no client cert) : 
1.  allow --kafka-tls-ca-cert without --kafka-tls-client-cert and --kafka-tls-client-key
1. and error messages when missing client-cert or client-key for Mutual TLS

2020-10-19 12:00 UTC, davidFR commented on kafka.go
> +var ErrorTLSMissingCert = errors.New("Missing client certificate")
Comment corrected

2020-10-19 12:00 UTC, davidFR commented on kafka.go
> +// ErrorTLS are the errors returned when TLS is misconfigured.
Comment corrected

2020-10-19 12:30 UTC, urbanishimwe requested changes
Thanks for the PR, I would suggest:

2020-10-19 12:30 UTC, urbanishimwe commented on kafka.go
> +		return &tlsConfig, ErrorTLSMissingCert
```suggestion
		return &tlsConfig, errors.New("missing TLS client certificate in kafka")
```

2020-10-19 12:30 UTC, urbanishimwe commented on kafka.go
> +		return &tlsConfig, ErrorTLSMissingKey
making them more descriptive

```suggestion
		return &tlsConfig, errors.New(mMissing key of client certificate in kafka")
```

2020-10-19 12:30 UTC, urbanishimwe commented on kafka.go
> +var ErrorTLSMissingCert = errors.New("Missing client certificate")
since they are used only once

```suggestion
```

2020-10-20 14:49 UTC, urbanishimwe approved these changes
I don't have a Kafka account to test this but ideally, it should be correct.

2020-11-02 04:14 UTC, merged